export const NEWBOOKING_REQUEST="NEWBOOKING_REQUEST"
export const NEWBOOKING_SUCCESS="NEWBOOKING_SUCCESS"
export const NEWBOOKING_FAIL="NEWBOOKING_FAIL"
export const NEWBOOKING_RESET="NEWBOOKING_RESET"



export const MYBOOKING_REQUEST="MYBOOKING_REQUEST"
export const MYBOOKING_SUCCESS="MYBOOKING_SUCCESS"
export const MYBOOKING_FAIL="MYBOOKING_FAIL"



export const ALLBOOKING_REQUEST="ALLBOOKING_REQUEST"
export const ALLBOOKING_SUCCESS="ALLBOOKING_SUCCESS"
export const ALLBOOKING_FAIL="ALLBOOKING_FAIL"


export const DELETEBOOKING_REQUEST="DELETEBOOKING_REQUEST"
export const DELETEBOOKING_SUCCESS="DELETEBOOKING_SUCCESS"
export const DELETEBOOKING_FAIL="DELETEBOOKING_FAIL"
export const DELETEBOOKING_RESET="DELETEBOOKING_RESET"
