export const ALLCELEBS_REQUEST = 'ALLCELEBS_REQUEST';
export const ALLCELEBS_SUCCESS = 'ALLCELEBS_SUCCESS';
export const ALLCELEBS_FAIL = 'ALLCELEBS_FAIL';


export const NEWCELEB_REQUEST="NEWCELEB_REQUEST"
export const NEWCELEB_SUCCESS="NEWCELEB_SUCCESS"
export const NEWCELEB_FAIL="NEWCELEB_FAIL"
export const NEWCELEB_RESET="NEWCELEB_RESET"

export const CELEBDETAIL_REQUEST="CELEBDETAIL_REQUEST"
export const CELEBDETAIL_SUCCESS="CELEBDETAIL_SUCCESS"
export const CELEBDETAIL_FAIL="CELEBDETAIL_FAIL"


export const UPDATECELEB_REQUEST="UPDATECELEB_REQUEST"
export const UPDATECELEB_SUCCESS="UPDATECELEB_SUCCESS"
export const UPDATECELEB_FAIL="UPDATECELEB_FAIL"
export const UPDATECELEB_RESET="UPDATECELEB_RESET"

export const DELETECELEB_REQUEST="DELETECELEB_REQUEST"
export const DELETECELEB_SUCCESS="DELETECELEB_SUCCESS"
export const DELETECELEB_FAIL="DELETECELEB_FAIL"
export const DELETECELEB_RESET="DELETECELEB_RESET"
