export const ALLMOVIES_REQUEST="ALLMOVIES_REQUEST"
export const ALLMOVIES_SUCCESS="ALLMOVIES_SUCCESS"
export const ALLMOVIES_FAIL="ALLMOVIES_FAIL"

export const NEWMOVIE_REQUEST="NEWMOVIE_REQUEST"
export const NEWMOVIE_SUCCESS="NEWMOVIE_SUCCESS"
export const NEWMOVIE_FAIL="NEWMOVIE_FAIL"
export const NEWMOVIE_RESET="NEWMOVIE_RESET"

export const MOVIEDETAIL_REQUEST="MOVIEDETAIL_REQUEST"
export const MOVIEDETAIL_SUCCESS="MOVIEDETAIL_SUCCESS"
export const MOVIEDETAIL_FAIL="MOVIEDETAIL_FAIL"

export const DELETEMOVIE_REQUEST="DELETEMOVIE_REQUEST"
export const DELETEMOVIE_SUCCESS="DELETEMOVIE_SUCCESS"
export const DELETEMOVIE_FAIL="DELETEMOVIE_FAIL"
export const DELETEMOVIE_RESET="DELETEMOVIE_RESET"

export const UPDATEMOVIE_REQUEST="UPDATEMOVIE_REQUEST"
export const UPDATEMOVIE_SUCCESS="UPDATEMOVIE_SUCCESS"
export const UPDATEMOVIE_FAIL="UPDATEMOVIE_FAIL"
export const UPDATEMOVIE_RESET="UPDATEMOVIE_RESET"

export const REVIEW_REQUEST="REVIEW_REQUEST"
export const REVIEW_SUCCESS="REVIEW_SUCCESS"
export const REVIEW_FAIL="REVIEW_FAIL"
export const REVIEW_RESET="REVIEW_RESET"

export const SEARCHMOVIE_REQUEST="SEARCHMOVIE_REQUEST"
export const SEARCHMOVIE_SUCCESS="SEARCHMOVIE_SUCCESS"
export const SEARCHMOVIE_FAIL="SEARCHMOVIE_FAIL"
export const SEARCHMOVIE_RESET="SEARCHMOVIE_RESET"