export const ALLTHEATRES_REQUEST="ALLTHEATRES_REQUEST"
export const ALLTHEATRES_SUCCESS="ALLTHEATRES_SUCCESS"
export const ALLTHEATRES_FAIL="ALLTHEATRES_FAIL"

export const THEATRES_REQUEST="THEATRES_REQUEST"
export const THEATRES_SUCCESS="THEATRES_SUCCESS"
export const THEATRES_FAIL="THEATRES_FAIL"


export const NEWTHEATRE_REQUEST="NEWTHEATRE_REQUEST"
export const NEWTHEATRE_SUCCESS="NEWTHEATRE_SUCCESS"
export const NEWTHEATRE_FAIL="NEWTHEATRE_FAIL"
export const NEWTHEATRE_RESET="NEWTHEATRE_RESET"

export const THEATREDETAIL_REQUEST="THEATREDETAIL_REQUEST"
export const THEATREDETAIL_SUCCESS="THEATREDETAIL_SUCCESS"
export const THEATREDETAIL_FAIL="THEATREDETAIL_FAIL"


export const UPDATETHEATRE_REQUEST="UPDATETHEATRE_REQUEST"
export const UPDATETHEATRE_SUCCESS="UPDATETHEATRE_SUCCESS"
export const UPDATETHEATRE_FAIL="UPDATETHEATRE_FAIL"
export const UPDATETHEATRE_RESET="UPDATETHEATRE_RESET"

export const DELETETHEATRE_REQUEST="DELETETHEATRE_REQUEST"
export const DELETETHEATRE_SUCCESS="DELETETHEATRE_SUCCESS"
export const DELETETHEATRE_FAIL="DELETETHEATRE_FAIL"
export const DELETETHEATRE_RESET="DELETETHEATRE_RESET"