
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const  LOADUSER_REQUEST="LOADUSER_REQUEST"
export const  LOADUSER_SUCCESS="LOADUSER_SUCCESS"
export const  LOADUSER_FAIL="LOADUSER_FAIL"

export const  LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const  LOGOUT_FAIL="LOGOUT_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ALLUSER_REQUEST="ALLUSER_REQUEST"
export const ALLUSER_SUCCESS="ALLUSER_SUCCESS"
export const ALLUSER_FAIL="ALLUSER_FAIL"

export const UPDATEUSER_REQUEST="UPDATEUSER_REQUEST"
export const UPDATEUSER_SUCCESS="UPDATEUSER_SUCCESS"
export const UPDATEUSER_FAIL="UPDATEUSER_FAIL"
export const UPDATEUSER_RESET="UPDATEUSER_RESET"

export const USERDETAIL_REQUEST="USERDETAIL_REQUEST"
export const USERDETAIL_SUCCESS="USERDETAIL_SUCCESS"
export const USERDETAIL_FAIL="USERDETAIL_FAIL"


export const DELETEUSER_REQUEST="DELETEUSER_REQUEST"
export const DELETEUSER_SUCCESS="DELETEUSER_SUCCESS"
export const DELETEUSER_FAIL="DELETEUSER_FAIL"
export const DELETEUSER_RESET="DELETEUSER_RESET"


export const USERLOCATION_REQUEST="USERLOCATION_REQUEST"
export const USERLOCATION_SUCCESS="USERLOCATION_SUCCESS"
export const USERLOCATION_FAIL="USERLOCATION_FAIL"